import { User } from '../migrations/00002-createTableUsers';

const roles = {
  admin: 'admin',
  customer: 'customer',
};

export const users: Omit<User, 'id'>[] = [
  {
    role: roles.customer,
    username: 'jdoe1',
    firstName: 'John',
    lastName: 'Doe',
    mail: 'jdoe1@example.com',
    phone: +441234567890,
    street: 'High Street',
    houseNumber: '10',
    apartmentNumber: 'A1',
    postcode: 'W1A 1AA',
    city: 'London',
    country: 'United Kingdom',
  },
  {
    role: roles.customer,
    username: 'asmith',
    firstName: 'Alice',
    lastName: 'Smith',
    mail: 'asmith@example.com',
    phone: +331234567890,
    street: 'Rue de Rivoli',
    houseNumber: '20',
    apartmentNumber: '',
    postcode: '75001',
    city: 'Paris',
    country: 'France',
  },
  {
    role: roles.customer,
    username: 'bwilliams',
    firstName: 'Bob',
    lastName: 'Williams',
    mail: 'bwilliams@example.com',
    phone: +491234567890,
    street: 'Münchner Straße',
    houseNumber: '30',
    apartmentNumber: '5B',
    postcode: '80331',
    city: 'Munich',
    country: 'Germany',
  },
  {
    role: roles.customer,
    username: 'cmiller',
    firstName: 'Carol',
    lastName: 'Miller',
    mail: 'cmiller@example.com',
    phone: +390612345678,
    street: 'Via Veneto',
    houseNumber: '40',
    apartmentNumber: '',
    postcode: '00187',
    city: 'Rome',
    country: 'Italy',
  },
  {
    role: roles.customer,
    username: 'djohnson',
    firstName: 'David',
    lastName: 'Johnson',
    mail: 'djohnson@example.com',
    phone: +34912345678,
    street: 'Calle de Alcalá',
    houseNumber: '50',
    apartmentNumber: '6C',
    postcode: '28014',
    city: 'Madrid',
    country: 'Spain',
  },
  {
    role: roles.customer,
    username: 'esmith',
    firstName: 'Emma',
    lastName: 'Smith',
    mail: 'esmith@example.com',
    phone: +31701234567,
    street: 'Damrak',
    houseNumber: '60',
    apartmentNumber: '',
    postcode: '1012 LP',
    city: 'Amsterdam',
    country: 'Netherlands',
  },
  {
    role: roles.customer,
    username: 'fwhite',
    firstName: 'Frank',
    lastName: 'White',
    mail: 'fwhite@example.com',
    phone: +41231234567,
    street: 'Bahnhofstrasse',
    houseNumber: '70',
    apartmentNumber: '3D',
    postcode: '8001',
    city: 'Zurich',
    country: 'Switzerland',
  },
  {
    role: roles.customer,
    username: 'gjones',
    firstName: 'Grace',
    lastName: 'Jones',
    mail: 'gjones@example.com',
    phone: +46701234567,
    street: 'Drottninggatan',
    houseNumber: '80',
    apartmentNumber: '',
    postcode: '111 60',
    city: 'Stockholm',
    country: 'Sweden',
  },
  {
    role: roles.customer,
    username: 'hking',
    firstName: 'Henry',
    lastName: 'King',
    mail: 'hking@example.com',
    phone: +35891234567,
    street: 'Mannerheimintie',
    houseNumber: '90',
    apartmentNumber: '7E',
    postcode: '00100',
    city: 'Helsinki',
    country: 'Finland',
  },
  {
    role: roles.customer,
    username: 'iweber',
    firstName: 'Isabel',
    lastName: 'Weber',
    mail: 'iweber@example.com',
    phone: +43123456789,
    street: 'Kärntner Straße',
    houseNumber: '100',
    apartmentNumber: '',
    postcode: '1010',
    city: 'Vienna',
    country: 'Austria',
  },
];
